name = "EchogramPlots"
uuid = "ca3b9080-f68d-11ea-2a4d-eba71caada40"
authors = ["Rob Blackwell <rob@robblackwell.com>"]
version = "0.1.0"

[deps]
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
